services:
  s1db:
    image: postgres:latest
    container_name: 68-s1-database
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_NAME}
    networks:
      - s1_network

  s1admin:
    image: dpage/pgadmin4
    container_name: 68-s1-admin
    ports:
      - ${PGADMIN_PORT}:80
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - s1db
    networks:
      - s1_network

  s1app:
    image: prawee/strapi:latest
    container_name: 68-s1-app
    ports:
      - ${APP_PORT}:5432
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
    depends_on:
      - s1db
    networks:
      - s1_network

networks:
  s1_network:
    driver: bridge